# Generated by Django 4.0 on 2024-01-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireHotspotDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('fireNum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Fire Hotspot District',
            },
        ),
        migrations.CreateModel(
            name='FireHotspotNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fireNum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Fire Hotspot National',
            },
        ),
        migrations.CreateModel(
            name='FireHotspotProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('fireNum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Fire Hotspot Protected Area',
            },
        ),
        migrations.CreateModel(
            name='FireHotspotProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('gid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fireNum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Fire Hotspot Province',
            },
        ),
        migrations.CreateModel(
            name='ForestCoverDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Forest Cover District',
            },
        ),
        migrations.CreateModel(
            name='ForestCoverNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Forest Cover National',
            },
        ),
        migrations.CreateModel(
            name='ForestCoverProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Protected Area',
            },
        ),
        migrations.CreateModel(
            name='ForestCoverProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('gid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Forest Cover Province',
            },
        ),
        migrations.CreateModel(
            name='GLADAlertDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'GLAD Alert District',
            },
        ),
        migrations.CreateModel(
            name='GLADAlertNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'GLAD Alert National',
            },
        ),
        migrations.CreateModel(
            name='GLADAlertProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'GLAD Alert Protected Area',
            },
        ),
        migrations.CreateModel(
            name='GLADAlertProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('gid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'GLAD Alert Province',
            },
        ),
        migrations.CreateModel(
            name='LandCoverDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_code', models.CharField(max_length=50)),
                ('landcover', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Land Cover District',
            },
        ),
        migrations.CreateModel(
            name='LandCoverNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('landcover', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Land Cover National',
            },
        ),
        migrations.CreateModel(
            name='LandCoverProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('landcover', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Land Cover Protected Area',
            },
        ),
        migrations.CreateModel(
            name='LandCoverProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('gid', models.IntegerField()),
                ('landcover', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Land Cover Province',
            },
        ),
        migrations.CreateModel(
            name='SARAlertDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('dist_code', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'SAR Alert District',
            },
        ),
        migrations.CreateModel(
            name='SARAlertNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'SAR Alert National',
            },
        ),
        migrations.CreateModel(
            name='SARAlertProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protected_area', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'SAR Alert Protected Area',
            },
        ),
        migrations.CreateModel(
            name='SARAlertProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('gid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('areaHa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'SAR Alert Province',
            },
        ),
    ]
